[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "solo"
dist-name = "solo-python"  # Unfortunately, `solo` is in use on PyPI
author = "SoloKeys"
author-email = "hello@solokeys.com"
home-page = "https://github.com/solokeys/solo-python"
requires-python = ">=3.6"
requires = [
  "click",
  "cryptography",
  "ecdsa",
  "fido2",
  "intelhex",
  "pyserial",
  "pyusb",
  "requests",
]
classifiers=[
    "License :: OSI Approved :: MIT License",
    "License :: OSI Approved :: Apache Software License",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
]

[tool.flit.scripts]
solo = "solo.cli:solo_cli"
