[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "pynitrokey"
dist-name = "pynitrokey"
author = "Nitrokey"
author-email = "pypi@nitrokey.com"
home-page = "https://github.com/Nitrokey/pynitrokey"
requires-python = ">=3.6"
description-file = "README.md"
requires = [
  "click >= 7.0",
  "cryptography",
  "ecdsa",
  "fido2 == 0.7.3",
  "intelhex",
  "pyserial",
  "pyusb",
  "requests",
  "pygments",
	"cffi"
]
classifiers=[
    "License :: OSI Approved :: MIT License",
    "License :: OSI Approved :: Apache Software License",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
]

[tool.flit.scripts]
nitropy = "pynitrokey.cli:nitropy"
